import {
  Home,
  Zap,
  TrendingUp,
  AreaChart,
  Bell,
  Key,
  Wallet,
  History,
  Search,
  Layers,
  Package,
  Settings as SettingsIcon,
  AlertTriangle,
  MessageCircle,
  Link as LinkIcon,
  Activity,
} from "lucide-react";

import {
  Dashboard,
  AdvancedOrders,
  Monitoring,
  PnLDashboard,
  RiskHeatmap,
  PredictiveAlerts,
  SentimentAnalysis,
  CrossChainBridge,
  LiquidityPools,
  JitoBundles,
  Settings,
  PortfolioDashboard,
  PortfolioPage,
  TradeHistory,
  MarketScreener,
  PerformanceAnalytics,
  NotificationsHub,
  APIKeysManager,
  TradingPage,
} from "./pages";

const routes = [
  {
    path: "/",
    label: "Dashboard",
    icon: Home,
    component: Dashboard,
    exact: true,
    needsDarkMode: true,
  },
  {
    path: "/terminal",
    label: "HFT Terminal",
    icon: Zap,
    component: Dashboard,
    needsDarkMode: true,
  },
  {
    path: "/trading",
    label: "Trading",
    icon: TrendingUp,
    component: TradingPage,
  },
  {
    path: "/portfolio",
    label: "Portfolio",
    icon: Wallet,
    component: PortfolioPage,
  },
  {
    path: "/history",
    label: "Trade History",
    icon: History,
    component: TradeHistory,
  },
  {
    path: "/screener",
    label: "Market Screener",
    icon: Search,
    component: MarketScreener,
  },
  {
    path: "/analytics",
    label: "Analytics",
    icon: AreaChart,
    component: PerformanceAnalytics,
  },
  {
    path: "/monitoring",
    label: "Monitoring",
    icon: Activity,
    component: Monitoring,
  },
  {
    path: "/notifications",
    label: "Notifications",
    icon: Bell,
    component: NotificationsHub,
  },
  {
    path: "/api-keys",
    label: "API Keys",
    icon: Key,
    component: APIKeysManager,
  },
  {
    path: "/advanced-orders",
    label: "Advanced Orders",
    icon: Zap,
    component: AdvancedOrders,
  },
  {
    path: "/pnl",
    label: "P&L Dashboard",
    icon: TrendingUp,
    component: PnLDashboard,
  },
  {
    path: "/risk",
    label: "Risk Heatmap",
    icon: AlertTriangle,
    component: RiskHeatmap,
  },
  {
    path: "/alerts",
    label: "Alerts",
    icon: Bell,
    component: PredictiveAlerts,
  },
  {
    path: "/sentiment",
    label: "Sentiment",
    icon: MessageCircle,
    component: SentimentAnalysis,
  },
  {
    path: "/bridge",
    label: "Cross-Chain",
    icon: LinkIcon,
    component: CrossChainBridge,
  },
  {
    path: "/liquidity",
    label: "Liquidity Pools",
    icon: Layers,
    component: LiquidityPools,
  },
  {
    path: "/bundles",
    label: "Jito Bundles",
    icon: Package,
    component: JitoBundles,
  },
  {
    path: "/settings",
    label: "Settings",
    icon: SettingsIcon,
    component: Settings,
  },
];

export default routes;
